#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "qui"
name = "Qui"
description.en = "qBittorrent web UI"
description.fr = "Interface utilisateur Web qBittorrent"

version = "1.19.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-2.0"
website = "https://getqui.com/"
admindoc = "https://getqui.com/docs/intro"
code = "https://github.com/autobrr/qui"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
     in_subdir = false
    amd64.url = "https://github.com/autobrr/qui/releases/download/v1.19.0/qui_1.19.0_linux_x86_64.tar.gz"
    amd64.sha256 = "0fedf33a4b1118e0f41b8c1831e0f153e4ff9776cd5a9ec0de983963453582c6"
    arm64.url = "https://github.com/autobrr/qui/releases/download/v1.19.0/qui_1.19.0_linux_arm64.tar.gz"
    arm64.sha256 = "fa319080c7e1fe4a014db8f133dfe4e77f1b2c41c37fefe806ce420be4787485"
    armhf.url = "https://github.com/autobrr/qui/releases/download/v1.19.0/qui_1.19.0_linux_x86_64.tar.gz"
    armhf.sha256 = "0fedf33a4b1118e0f41b8c1831e0f153e4ff9776cd5a9ec0de983963453582c6"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*_linux_x86_64.tar.gz"
    autoupdate.asset.armhf = ".*_linux_x86_64.tar.gz"
    autoupdate.asset.arm64 = ".*_linux_arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
